"""Pydantic AI/ML models: signals, predictions, risk assessments, and AGI decisions."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class SignalDirection(str, Enum):
    """Directional signal from a trading model."""

    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"


class SignalStrength(str, Enum):
    """Qualitative strength of a trading signal."""

    WEAK = "WEAK"
    MODERATE = "MODERATE"
    STRONG = "STRONG"
    VERY_STRONG = "VERY_STRONG"


class DecisionAction(str, Enum):
    """High-level action emitted by the AGI orchestrator."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE = "CLOSE"
    REDUCE = "REDUCE"


class TradingSignal(BaseModel):
    """A directional signal generated by a single model or strategy."""

    signal_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    source: str  # e.g. "momentum_model", "sentiment_analyzer"
    symbol: str
    direction: SignalDirection
    strength: SignalStrength = SignalStrength.MODERATE
    confidence: float = Field(ge=0.0, le=1.0)
    target_price: Optional[Decimal] = None
    stop_price: Optional[Decimal] = None
    horizon_minutes: Optional[int] = None
    features: Dict[str, Any] = Field(default_factory=dict)
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = {"frozen": True}


class ModelPrediction(BaseModel):
    """Output from a single ML model inference."""

    prediction_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    model_name: str
    model_version: str = "1.0.0"
    symbol: str
    predicted_return: float  # fractional return, e.g. 0.02 = +2 %
    predicted_direction: SignalDirection
    confidence: float = Field(ge=0.0, le=1.0)
    feature_importance: Dict[str, float] = Field(default_factory=dict)
    raw_output: Dict[str, Any] = Field(default_factory=dict)
    inference_latency_ms: Optional[float] = None
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = {"frozen": True}


class RiskAssessment(BaseModel):
    """Pre-trade risk evaluation result."""

    assessment_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str
    proposed_quantity: Decimal = Field(gt=Decimal("0"))
    proposed_notional_usd: Decimal = Field(default=Decimal("0"))
    current_drawdown_pct: float = Field(ge=0.0)
    is_approved: bool
    risk_score: float = Field(ge=0.0, le=1.0)
    rejection_reasons: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = {"frozen": True}


class AGIDecision(BaseModel):
    """Composite decision from the AGI orchestrator."""

    decision_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    symbol: str
    action: DecisionAction
    quantity: Optional[Decimal] = Field(default=None, gt=Decimal("0"))
    target_price: Optional[Decimal] = Field(default=None, gt=Decimal("0"))
    confidence: float = Field(ge=0.0, le=1.0)
    signals: List[TradingSignal] = Field(default_factory=list)
    predictions: List[ModelPrediction] = Field(default_factory=list)
    risk_assessment: Optional[RiskAssessment] = None
    rationale: str = ""
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = {"frozen": True}
